name = "SimulacoesPedro"
uuid = "cef8faa8-d13d-4d33-9844-1be51716b098"
authors = ["Pedro Mariz <pomc.usp@gmail.com> and contributors"]
version = "0.1.0"

[deps]
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"

[compat]
Parameters = "0.12"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
